option(SHADERC_SKIP_INSTALL "Skip installation" ON)
option(SHADERC_SKIP_TESTS "Skip building tests" ON)
option(SHADERC_SKIP_EXAMPLES "Skip building examples" ON)
option(SHADERC_SKIP_COPYRIGHT_CHECK "Skip copyright check" OFF)
option(SHADERC_ENABLE_WERROR_COMPILE "Enable passing -Werror to compiler, if available" ON)
option(SHADERC_ENABLE_SHARED_CRT "Use the shared CRT instead of the static CRT" OFF)
if (WIN32)
    set(PYTHON_EXECUTABLE python)
endif()
add_definitions(-D_CRT_SECURE_NO_WARNINGS)
add_subdirectory(shaderc)